# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField()),
                ('bloodgroup', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='faculty')),
                ('barcode_serial', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='facultyTemplateDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=120)),
                ('collegeNameFont', models.CharField(max_length=120)),
                ('collegeNameFontSize', models.IntegerField()),
                ('addressLine1', models.CharField(max_length=120)),
                ('addline1font', models.CharField(max_length=120)),
                ('addline1fontsize', models.IntegerField()),
                ('addressLine2', models.CharField(max_length=120)),
                ('addressLine3', models.CharField(max_length=120)),
                ('addressLine4', models.CharField(max_length=120)),
                ('addressLine5', models.CharField(max_length=120)),
                ('addressLine2To5Font', models.CharField(max_length=120)),
                ('addressLine2To5FontSize', models.IntegerField()),
                ('detailsFont', models.CharField(max_length=120)),
                ('detailsFontSize', models.IntegerField()),
                ('parentLogo', models.ImageField(blank=True, null=True, upload_to='template_faculty')),
                ('principalSign', models.ImageField(blank=True, null=True, upload_to='template_faculty')),
                ('backgroundDesign', models.ImageField(blank=True, null=True, upload_to='template_faculty')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('typ', models.CharField(max_length=10)),
                ('admissionNumber', models.CharField(max_length=200, unique=True)),
                ('validtill', models.DateField()),
                ('dateofbirth', models.DateField()),
                ('bloodgroup', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('contact1', models.CharField(max_length=10)),
                ('contact2', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student')),
                ('clss', models.CharField(blank=True, max_length=5, null=True)),
                ('rollno', models.CharField(blank=True, max_length=5, null=True)),
                ('barcode_serial', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentTemplateDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=120)),
                ('collegeNameFont', models.CharField(max_length=120)),
                ('collegeNameFontSize', models.IntegerField()),
                ('addressLine1', models.CharField(max_length=120)),
                ('addressLine2', models.CharField(max_length=120)),
                ('addressLine3', models.CharField(max_length=120)),
                ('addressLine4', models.CharField(max_length=120)),
                ('addressLine5', models.CharField(max_length=120)),
                ('addressLine1To5Font', models.CharField(max_length=120)),
                ('addressLine1To5FontSize', models.IntegerField()),
                ('detailsFont', models.CharField(max_length=120)),
                ('detailsFontSize', models.IntegerField()),
                ('collegeLogo', models.ImageField(blank=True, null=True, upload_to='template_student')),
                ('parentLogo', models.ImageField(blank=True, null=True, upload_to='template_student')),
                ('principalSign', models.ImageField(blank=True, null=True, upload_to='template_student')),
                ('backgroundDesign', models.ImageField(blank=True, null=True, upload_to='template_student')),
            ],
        ),
    ]
